name: Github Actions # 워크플로우의 이름을 설정합니다. 이 이름은 GitHub Actions에서 워크플로우를 식별하는 데 사용됩니다.

on:
  push:
    branches:
      - 'develop' # 이 워크플로우는 'develop' 브랜치에 push 이벤트가 발생할 때 실행됩니다.
    paths:
      - '' # 이 워크플로우는 모든 경로에서의 변경 사항에 대해 실행됩니다.

jobs:
  build:
    runs-on: ubuntu-latest # 이 작업은 'ubuntu-latest' 환경에서 실행됩니다.

    steps:
    - name: Print a message # 이 단계의 이름을 설정합니다. 이 이름은 GitHub Actions 로그에서 이 단계를 식별하는 데 사용됩니다.
      run: echo "Hello, GitHub Actions!" # 이 단계에서는 "Hello, GitHub Actions!"라는 메시지를 출력합니다.
